# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Compilation Database
        # Clang-tidy needs to know your header paths and macros. 
        # This command tells CMake to generate that info without building the whole project.
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run C++ Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: 'google' # Options: 'google', 'llvm', 'mozilla', or 'file' (if you have a .clang-format)
          tidy-checks: 'bugprone-*,performance-*,readability-*'
          thread-comments: true # Posts results directly on your PR
          database: 'build' # Points to the file generated in the previous step
          files-changed-only: false
          lines-changed-only: false
          files-filter: '^(src|include)/.*\.(cpp|h|hpp)$'

  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dmn .

      - name: Run container tests
        run: docker run --rm dmn


