# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Generate Compilation Database
#        # Clang-tidy needs to know your header paths and macros. 
#        # This command tells CMake to generate that info without building the whole project.
#        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && cmake --build build/
#
#      - name: Run C++ Linter
#        uses: cpp-linter/cpp-linter-action@v2
#        id: linter
#        with:
#          style: 'llvm'
#          version: '18'
#          tidy-checks: 'bugprone-*,performance-*,readability-*'
#          thread-comments: true
#
#          # 1. Define exactly which file extensions to look for
#          extensions: 'cpp,hpp'
#
#          # 2. Filter to ONLY include files in src/ or include/
#          # This regex matches any path starting with src/ or include/
#          files-filter: '^(src|include)/.*'
#
#          # 3. Ensure it doesn't just look at PR changes
#          files-changed-only: false
#
#          # 4. Point to your compile commands
#          database: 'build'

  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dmn .

      - name: Run container tests
        run: docker run --rm dmn


